#!/usr/bin/env bash

app=${1:-$APPNAME}

heroku config -s --app $app > .env

git remote -v | grep heroku
if [ "$?" = "1" ]; then
  heroku git:remote -a $app
fi

heroku buildpacks:clear
heroku buildpacks:add https://github.com/TBSR/heroku-buildpack-cairo.git
heroku buildpacks:add heroku/nodejs
